stages:
  - build
  - test
  - clean
  - staging
  - deploy

variables:
  COMPOSE_DEV: "docker-compose -p dev_$CI_COMMIT_SHORT_SHA -f docker-compose.dev.yml"
  COMPOSE_TEST: "docker-compose -p test_$CI_COMMIT_SHORT_SHA -f docker-compose.prod.base.yml -f docker-compose.prod.test.yml"
  COMPOSE_DEPLOY: "docker-compose -f docker-compose.prod.base.yml -f docker-compose.prod.deploy.yml"
  BUILD_WAIT: "1m"
  DEPLOY_WAIT: "10s"

before_script:
  - echo "COMPOSE_TEST = $COMPOSE_TEST"
  - echo "COMPOSE_DEPLOY = $COMPOSE_DEPLOY"
  - echo "BUILD_WAIT = $BUILD_WAIT"
  - echo "DEPLOY_WAIT = $DEPLOY_WAIT"

build:
  stage: build
  tags:
    - comp8755
    - cooper
  script:
    - export LDAP_ADDR="ldap://$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')"
    - $COMPOSE_TEST build
    - $COMPOSE_TEST up -d
    - sleep $BUILD_WAIT  # Run for sometime before checking
    - ./tests/compose-check.sh "$COMPOSE_TEST"  # Check run normally
    - $COMPOSE_TEST stop
    - ./tests/compose-check.sh "$COMPOSE_TEST"  # Check stop normally
    - $COMPOSE_TEST up -d  # Restart in prepare for running the test
    - sleep $DEPLOY_WAIT  # Make sure everything is fully initialized

#test-lint:
#  stage: test
#  tags:
#    - comp8755
#    - cooper
#  allow_failure: true
#  script:
#    - $COMPOSE_TEST exec -T django-gunicorn pylint --load-plugins pylint_django accounts research_mgt srpms
#    - $COMPOSE_TEST run angular-client ng lint

test-front-end:
  stage: test
  tags:
    - comp8755
    - cooper
  script:
    - export LDAP_ADDR="ldap://$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')"
    - $COMPOSE_TEST run angular-client ng test --watch=false --browsers=Chrome_without_sandox  # Front-end test

test-back-end:
  stage: test
  tags:
    - comp8755
    - cooper
  script:
    - export LDAP_ADDR="ldap://$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')"
    - $COMPOSE_TEST exec -T django-gunicorn coverage run --source='.' manage.py migrate  # Test migration
    - $COMPOSE_TEST exec -T django-gunicorn coverage run --source='.' manage.py migrate accounts zero
    - $COMPOSE_TEST exec -T django-gunicorn coverage run --source='.' manage.py migrate
    - $COMPOSE_TEST exec -T django-gunicorn coverage run --source='.' --omit='*/tests*,srpms/*' manage.py test --noinput  # NOTE: Coverage is inaccurate when run in parallel
    - $COMPOSE_TEST exec -T django-gunicorn coverage report

clean:
  stage: clean
  tags:
    - comp8755
    - cooper
  when: always
  script:
    - $COMPOSE_TEST down --rmi 'local' -v --remove-orphans

prod-staging:
  stage: staging
  tags:
    - comp8755
    - srpms
  script:
    - $COMPOSE_DEPLOY build
  only:
    - master

prod-deploy:
  stage: deploy
  tags:
    - comp8755
    - srpms
  when: manual
  script:
    - $COMPOSE_DEPLOY up -d
    - sleep $DEPLOY_WAIT
    - ./tests/compose-check.sh "$COMPOSE_DEPLOY"
    - sleep $BUILD_WAIT  # Wait longer to see if anything happen
    - ./tests/compose-check.sh "$COMPOSE_DEPLOY"
  only:
    - master
