# Deployment override, for production environment. Please do not run this in environment that
# does not have public IP, otherwise the HTTPS certificate would not obtain successfully.
#
# Author: Dajie Yang (u6513788)
# Email: dajie.yang@anu.edu.au
version: '3.7'

services:
  nginx:
    ports:
      # Map host 80 to container 80
      - 80:80
      - 443:443

  angular-client:
    build:
      args:
        - TEST=False

  # Manage Let's Encrypt SSL certificate
  #
  # Note that this container is not part of the srpms network, but
  # connect to the host in order to support docker-compose-in-docker.
  # By doing this we can renew certificate, and reload nginx within
  # this container.
  certbot:
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    env_file:
      - config.prod/certbot.env
      - config.prod/general.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt_volume:/etc/letsencrypt
      - certbot_volume:/var/www/certbot
    network_mode: host
    depends_on:
      - nginx

secrets:
  postgres_db:
    file: /srpms-secrets/postgres-db.txt
  postgres_user:
    file: /srpms-secrets/postgres-user.txt
  postgres_passwd:
    file: /srpms-secrets/postgres-passwd.txt
  postgres_init_args:
    file: /srpms-secrets/postgres-init-args.txt
  django_secret_key:
    file: /srpms-secrets/django_secret_key.txt
