# Please note that this compose file is for development only, please
# use docker-compose.production.yml for production override
version: '3'

services:
  django-gunicorn:
    build:
      context: ./srpms
      dockerfile: ./Dockerfile
      args:
        - DEBUG=True
    volumes:
      - ./srpms:/djangoproj/srpms
    environment:
      - LDAP_ADDR=${LDAP_ADDR}
    env_file:
      - ./config.dev/db-postgres.env
      - ./config.dev/django-gunicorn.env
      - ./config.dev/general.env
    networks:
      - srpms_network
    depends_on:
      - db-postgres
    stdin_open: true
    tty: true

  # For development purpose only
  angular-client:
    build:
      context: ./srpms-client
      dockerfile: ./Dockerfile
      args:
        - DEBUG=True
    env_file:
      - ./config.dev/general.env
    volumes:
      - ./srpms-client:/app/srpms-client
      - angular_volume:/dist
    networks:
      - srpms_network

  nginx:
    build: ./nginx
    ports:
      - 8000:80
      - 8001:443
    env_file:
      - ./config.dev/certbot.env
    volumes:
      # Ngnix configuration file
      - ./config.dev/nginx/conf.d:/etc/nginx/conf.d
      - angular_volume:/dist
    networks:
      - srpms_network
    depends_on:
      - django-gunicorn
      - angular-client

  db-postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    volumes:
      - db_postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./config.dev/db-postgres.env
    networks:
      - srpms_network

networks:
  srpms_network:
    driver: bridge

volumes:
  db_postgres_volume:
  angular_volume:
