version: '3'

services:
  django-gunicorn:
    build: ./srpms
    volumes:
      - ./srpms:/djangoproj/srpms
      - static_volume:/djangoproj/srpms/static
      - media_volume:/djangoproj/srpms/media
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - srpms_network
    depends_on:
      - db-postgres

  nginx:
    image: nginx:1.17-alpine
    ports:
      #  Map host 8000 to container 80
      - 8000:80
    volumes:
      # Ngnix configuration file
      - ./config.dev/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/djangoproj/srpms/static
      - media_volume:/djangoproj/srpms/media
    networks:
      - srpms_network
    depends_on:
      - django-gunicorn

  db-postgres:
    image: postgres:11.5-alpine
    volumes:
      - db_postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    networks:
      - srpms_network

networks:
  srpms_network:
    driver: bridge

volumes:
  db_postgres_volume:
  static_volume:
  media_volume:

