# Generated by Django 2.2.1 on 2019-09-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('max_mark', models.IntegerField()),
                ('min_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('resources', models.CharField(blank=True, max_length=200)),
                ('convener_approval_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('convener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convene', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProject',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research_mgt.Contract')),
                ('title', models.CharField(max_length=100)),
                ('objectives', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
            bases=('research_mgt.contract',),
        ),
        migrations.CreateModel(
            name='SpecialTopics',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research_mgt.Contract')),
                ('title', models.CharField(max_length=100)),
                ('objectives', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
            bases=('research_mgt.contract',),
        ),
        migrations.AddField(
            model_name='contract',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research_mgt.Course'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_formal', models.BooleanField()),
                ('supervisor_approval_date', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='research_mgt.Contract')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'supervisor', 'contract')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_description', models.CharField(blank=True, max_length=200)),
                ('due', models.DateField(blank=True, null=True)),
                ('max_mark', models.IntegerField()),
                ('examiner_approval_date', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_method', to='research_mgt.Contract')),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examine', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_method', to='research_mgt.AssessmentTemplate')),
            ],
            options={
                'unique_together': {('id', 'contract', 'examiner')},
            },
        ),
    ]
