# Generated by Django 2.2.1 on 2019-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_number', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('report', models.PositiveSmallIntegerField(default=45)),
                ('artefact', models.PositiveSmallIntegerField(default=45)),
                ('supervisor', models.CharField(max_length=100)),
                ('examinor', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
    ]
