# This compose file is for the Runner of the GitLab CI pipeline
#
# Author: Dajie Yang (u6513788)
# Email: dajie.yang@anu.edu.au

version: '3'

services:
  runner:
    build: .
    restart: always
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
